version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  mongo-seed:
    build: ./mongo_seed
    depends_on:
      - mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

  api:
    build: .
    restart: always
    depends_on:
      - mongo
    ports:
      - 4000:4000
